<h1> My Notebook </h1>
<p>
    This is my first notebook.
</p>

In [4]:
2 + 5

7

In [5]:
print("Hello")

Hello


<p>
The first is when you modify sth, reload everytime.
</p>
<p>
The last for making graphs here, not in other window
</p>

In [6]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from math import sqrt

In [9]:
sqrt(81)

9.0

In [10]:
u = np.array([2,-7,1])

In [11]:
u

array([ 2, -7,  1])

In [12]:
v = np.array([-3, 0, 4])

In [13]:
v

array([-3,  0,  4])

In [14]:
A = np.array([[1,2,0],[3,-1,4]])

In [15]:
A

array([[ 1,  2,  0],
       [ 3, -1,  4]])

In [16]:
B = np.array([[2, -1],[1, 0],[-3, 4]])

In [17]:
B

array([[ 2, -1],
       [ 1,  0],
       [-3,  4]])

In [18]:
u + v

array([-1, -7,  5])

In [19]:
-3 * u

array([-6, 21, -3])

In [20]:
u * v

array([-6,  0,  4])

In [21]:
u.dot(v)

-2

In [22]:
np.dot(u,v)

-2

In [23]:
product = u.dot(u)

In [24]:
product

54

In [25]:
sqrt(product)

7.3484692283495345

In [26]:
u * u

array([ 4, 49,  1])

In [27]:
A + A

array([[ 2,  4,  0],
       [ 6, -2,  8]])

In [28]:
A + u #illegal in maths but broadcasting in numpy

array([[ 3, -5,  1],
       [ 5, -8,  5]])

In [29]:
10 * A

array([[ 10,  20,   0],
       [ 30, -10,  40]])

In [30]:
A.dot(v)

array([-3,  7])

In [31]:
np.dot(A,B)

array([[ 4, -1],
       [-7, 13]])

In [32]:
A.transpose() #A.T

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

In [33]:
np.dot(A, A.transpose())

array([[ 5,  1],
       [ 1, 26]])

In [34]:
np.dot(A.transpose(), A)

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

In [35]:
u.min()

-7

In [36]:
u.argmin()

1

In [37]:
u.mean()

-1.3333333333333333

<p>
    Exercise
</p>
<p>
    Play with the cumsum method on 1-dimensional numpy arrays.Define a Python function that does the same thing for regular Python lists. Then compare how long they take to run on an arraylist that contains all the integers from 1 to 1000 inclusive.
</p>

In [26]:
#cumsum method in numpy
%timeit np.cumsum(range(1,1001))

156 µs ± 322 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
#cumsum method defined by LDP
def my_cumsum(array):
    cumsum_array = []
    cumsum_array.append(array[0])
    for i in range(1,len(array)):
        cumsum_array.append(cumsum_array[i-1] + array[i])
    return cumsum_array

%timeit my_cumsum(list(range(1,1001)))


        

230 µs ± 351 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
